// Produces a self-contained stylesheet for the design-sync bundle: the design
// tokens (src/styles/tokens.css) inlined ahead of the component rules
// (src/styles/app.css), with app.css's `@import "./tokens.css"` stripped so the
// emitted _ds_bundle.css has no dangling root-relative import (the preview cards
// link _ds_bundle.css directly, so it must stand alone). Wired as cfg.buildCmd
// → cfg.cssEntry; re-run on every sync so token/style edits propagate.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..');
const tokens = readFileSync(join(repo, 'src/styles/tokens.css'), 'utf8');
const app = readFileSync(join(repo, 'src/styles/app.css'), 'utf8')
  .replace(/^[ \t]*@import\s+["']\.\/tokens\.css["'];?[ \t]*\n?/m, '');

const out = join(here, 'ds-bundle-styles.css');
writeFileSync(
  out,
  `/* GENERATED by .design-sync/build-css.mjs — do not edit. */\n` +
    `/* Design tokens (tokens.css) + component styles (app.css), self-contained. */\n\n` +
    tokens +
    `\n\n/* ── component styles (app.css) ───────────────────────────────── */\n` +
    app,
);
console.error(`build-css: wrote ${out} (${(readFileSync(out).length / 1024).toFixed(0)} KB)`);
