// Types for the vendored Observatory datasets (SPEC-stats-dashboard §4.3).
// The JSON files are generated by scripts/build-observatory-data.mjs; shape
// correctness is enforced there (build time) and in data.test.ts (CI time).
// index.ts is the single cast boundary — nothing else imports the JSON.

export type TrioModality = "auditory" | "visual" | "interoceptive";

export type ThesisPair = {
  pairing: string;
  modality: TrioModality;
  romaji: string;
  /** Recomputed nCorrect / n, 4 dp. */
  accuracy: number;
  nCorrect: number;
  n: number;
  /** 1–7 scale. */
  meanRating: number;
  medianRtMs: number;
  /** meanRating standardized within the 30 thesis pairs (scatter y-axis). */
  meanRatingZ: number;
};

export type ThesisModalityAggregate = {
  /** Weighted Σ nCorrect / Σ n across the modality's pairs. */
  accuracy: number;
  n: number;
  meanRating: number;
  pairs: number;
};

export type ThesisPairsFile = {
  meta: {
    source: string;
    citation: string;
    license: string;
    generatedBy: string;
    pairCount: number;
    ratingScale: string;
    /** Mean/SD behind meanRatingZ — reused for the session crosshair math. */
    ratingMean: number;
    ratingSd: number;
  };
  byModality: Record<TrioModality, ThesisModalityAggregate>;
  pairs: ThesisPair[];
};

export type McleanStratum = "ideophone" | "prosaic";

export type McleanItem = {
  id: string;
  word: string;
  concept: string;
  stratum: McleanStratum;
  /** Proportion correct, 2AFC guessing, 0–1. */
  guessScore: number;
  guessZ: number;
  /** Iconicity rating, normalized 0–1 (their published coding). */
  ratingScore: number;
  /** Published z within the 304 items — the scatter's y value for this layer. */
  ratingZ: number;
};

export type McleanFile = {
  meta: {
    source: string;
    citation: string;
    license: string;
    generatedBy: string;
    itemCount: number;
    ideophoneCount: number;
    prosaicCount: number;
    scales: Record<string, string>;
  };
  items: McleanItem[];
};

/** Fixed axis order: auditory, visual, haptic, gustatory, olfactory, interoceptive. */
export type NormsAxes = readonly [number, number, number, number, number, number];

export type NormsWord = {
  word: string;
  /** Perceptual strength 0–5 per axis, in meta.axisOrder order. */
  axes: NormsAxes;
  /** Strict romaji-equality match against the arena pool; null = no match. */
  arena: { romaji: string; gloss: string } | null;
};

export type NormsFile = {
  meta: {
    source: string;
    citation: string;
    license: string;
    generatedBy: string;
    wordCount: number;
    axisOrder: readonly string[];
    axisMax: number;
    arenaMatchCount: number;
    defaultPair: readonly [string, string];
    defaultPairL1: number;
  };
  words: NormsWord[];
};

export type ArenaPoolWord = { romaji: string; gloss: string };

export type ArenaPoolFile = {
  meta: {
    source: string;
    note: string;
    generatedBy: string;
    wordCount: number;
  };
  words: ArenaPoolWord[];
};
